// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCicfUmKbatJEOXuwYjIhdk5W8zGpkRdO0',
    appId: '1:295374597060:web:cb8356da5daf71fd785291',
    messagingSenderId: '295374597060',
    projectId: 'preloved-uas-project',
    authDomain: 'preloved-uas-project.firebaseapp.com',
    storageBucket: 'preloved-uas-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3XhZBtJeNDSJa-KYDvMZqM7f9RDkxPY',
    appId: '1:295374597060:android:d18eabaa0122e3c8785291',
    messagingSenderId: '295374597060',
    projectId: 'preloved-uas-project',
    storageBucket: 'preloved-uas-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZVs9-O6BZM10TZ3v42T6Bccu-_IWpmw',
    appId: '1:295374597060:ios:dc1c771f32bdd2f6785291',
    messagingSenderId: '295374597060',
    projectId: 'preloved-uas-project',
    storageBucket: 'preloved-uas-project.firebasestorage.app',
    iosBundleId: 'com.example.pabtugasuas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZVs9-O6BZM10TZ3v42T6Bccu-_IWpmw',
    appId: '1:295374597060:ios:dc1c771f32bdd2f6785291',
    messagingSenderId: '295374597060',
    projectId: 'preloved-uas-project',
    storageBucket: 'preloved-uas-project.firebasestorage.app',
    iosBundleId: 'com.example.pabtugasuas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCicfUmKbatJEOXuwYjIhdk5W8zGpkRdO0',
    appId: '1:295374597060:web:d0f43bc2767e6b70785291',
    messagingSenderId: '295374597060',
    projectId: 'preloved-uas-project',
    authDomain: 'preloved-uas-project.firebaseapp.com',
    storageBucket: 'preloved-uas-project.firebasestorage.app',
  );
}
